### ISSUE TITLE
USER STORY: Deploy site

### ISSUE THREAD

**Issue by saziosu** [saziosu/book-swap#1]
As a **Developer**, I can **deploy the website early** so that I can **avoid any technical issues or stress later in the project**

**Acceptance Criteria:**

- The project must be deployed to Heroku
- The code must be stored in GitHub
- The code must be written on CodeAnywhere
- The database must use an external database like ElephantSQL
- Images must be stored on an external host like Cloudinary

**Tasks:**

*  [x] Create workspace with Code Anywhere
*  [x] Install dependancies (Django, Psycopg2, gunicorn, cloudinary)
*  [x] Connect Github to Heroku
*  [x] Connect Cloudinary
*  [x] Connect ElephantSQL/PostGres
*  [x] Set up environment variables
*  [x] Ensure app is showing deployed on Heroku

**Comment by saziosu** [comment]
Added the workspace in CodeAnywhere

**Comment by saziosu** [comment]
Followed the deployment walkthrough and set up the requirements for the project and Heroku deployment.
The Heroku app is now also showing django installed and running successfully.
