### ISSUE TITLE
USER STORY: Delete Book Posts

### ISSUE THREAD

**Issue by saziosu** [saziosu/book-swap#13]
**Epic:** #5 

As a **User**, I can **edelete my book post** so that I can **manage my posts**

**Acceptance Criteria:**

- Users must be able to delete their book post
- Users should confirm that they would like to delete the post
- Only the User that created the post should be able to delete it

**Tasks:**

- [x] Add the DeleteView view for deletion
    - [x] Within this view, only allow the user that made the post to update
- [x] Add a warning to the template to confirm the user wants to delete *this* post
    - [x] Set up a cancel button to bring the user back to the page, if they selected the wrong post
- [ ] Add the delete button to the book posts for the post owner.
- [x] Wire up the url

**Comment by saziosu** [comment]
Added book_delete.html and wired up the url.
This is successfully deleting the appropriate post.
Next steps will be adding the cancel deletion button and adding the delete buttons to the posts.

**Comment by saziosu** [comment]
Added the cancel deletion button to the deletion page.
This brings the user back via the window history if they went to cancel the wrong post.

**Comment by saziosu** [comment]
Added the deletion buttons to index.html and book_detail.html to allow the user on the front end to delete the posts.
This is only seen by users that made the individual post.
