### ISSUE TITLE
USER STORY: Styling & Layout

### ISSUE THREAD

**Issue by saziosu** [saziosu/book-swap#17]
**Epic:** #16 

As a **User**, I can **view a clean and attractive website** so that I can **have a positive experience**

**Acceptance Criteria:**

- The css, colours used and images should be fitting with the theme of the website
- The structure of the posts should be well laid out and consistent across the site

**Tasks:**

*  [x] Update html and templated structure and layout
    *  [x] base.html
    *  [x] index.html
    *  [x] book_detail.html
    *  [x] book_form.html
    * [x] book_delete.html
*  [x] Update css and bootstrap with improved styling
    *  [x] base.html
    *  [x] index.html
    *  [x] book_detail.html
    *  [x] book_form.html
    * [x] book_delete.html
* [x] Add and style custom 404 and 403 pages.
* [x] Add favicon
* [x]  Add the `add your book` link to the navbar, only for logged in users.

**Comment by saziosu** [comment]
Changed the color of the book post cards on index.html to better line up with the colour palette

**Comment by saziosu** [comment]
Added an image logo to the navbar brand to bring a more cohesive look to the navbar at the top of the page.

**Comment by saziosu** [comment]
Added further details and styling to book_detail.html
Included a border on the image with a colour to match the chosen colour palette.
Added the Book's Genre and added flex to give a better layout to bootstrap

**Comment by saziosu** [comment]
Updated the comments in index.html, book_detail.html and style.css for better readability.
I also updated index.html to use sections to improve the semantics.

**Comment by saziosu** [comment]
Updated book_form.html to improve the sizing on the front end and add some margins to the top and bottom to give space between the navbar and the footer.

**Comment by saziosu** [comment]
Book_delete.html:
Updated the heading size.
Adding some padding and margins and changed alignment to have a better look to the page.
Updated the comments to improve reading.

**Comment by saziosu** [comment]
Added 404, 403 and 500 error pages.
I also went ahead and edited the allauth templates to improve the signup,sign in and logout on the front end.

**Comment by saziosu** [comment]
Ran into errors on the 404, 403 and 500 error pages, found that I had forgotten to add the endblock tags to the ends of the files.
This is now resolved.

**Comment by saziosu** [comment]
Added favicon files and updated base.html to include these on the front end

**Comment by saziosu** [comment]
Updated style.css with media queries to improve the responsiveness on smaller devices

**Comment by saziosu** [comment]
Added `add your book` to the navbar and also included an anchor link to jump down to the current book posts.
