### ISSUE TITLE
USER STORY: Account creation

### ISSUE THREAD

**Issue by saziosu** [saziosu/book-swap#3]
**Epic:** #2 

- As a **User**, I can **create an account** so that I can **access features for authenticated users**

**Acceptance Criteria:**

- Users must provide their information to create an account (name, email, phone number)
- Users must be able to log in and log out after the account has been created
- Users should be able to update their information (email, phone number)
- Users must be able to delete their account

**Tasks:**

*  [x] Install django-allauth
*  [x] Add navigation style to the front end
*  [x] Create the templates for registration, login and logout

**Comment by saziosu** [comment]
Installed django-allauth and added the signup/login/logout links to base.html

**Comment by saziosu** [comment]
Updated the login/logout/signup templates to extend from base.html
