### ISSUE TITLE
USER STORY: Create Book Post

### ISSUE THREAD

**Issue by saziosu** [saziosu/book-swap#6]
**Epic:** #5 

As a **User**, I can **create a book post** so that I can **other users can decide if they would like to swap**

**Acceptance Criteria:**

- The book post must include the user's name and date the post was created
- The book post must have the user state the book title/description/author
- The book post should allow the user to include the genre of the book
- The book posts should give the option to add a photo/image
    - A placeholder should be added if no photo/image is supplied
- The book post should have the user state the condition of the book
- The editor should include summernote

**Tasks:**

- [x] Create the template for post creation
- [x] Create the views for post creation
- [x] Add crispyforms
- [x] Wire up the urls
- [x]  Add absolute url to model

**Comment by saziosu** [comment]
Installed crispy forms and added to the requirements.txt
I plan to use crispy forms for better formatting on the forms for creating posts, this will also be useful for editing posts at a later date.

**Comment by saziosu** [comment]
Added the BookCreateView and wired up the url for it.
The template will include crispy forms for formatting

**Comment by saziosu** [comment]
Added the bookpost_form.html template and got this running on the front end.
Ran into a bug when trying to apply crispy forms, will come back to this at another date.

Currently the form can be submitted but requires the absolute url on the model to redirect to the correct book post

**Comment by saziosu** [comment]
Resolved the bug with crispy forms, books are able to be added and I have updated the styling on the book form to improve the design

**Comment by saziosu** [comment]
Moved the book form into forms.py and updated the absolute_url to redirect the user to the book detail of the post they just created.
Also updated the book form template to encourage unauthenticated users to log in to make a post.

**Comment by saziosu** [comment]
Next steps, I plan to add the link to add a book to the front end so that it can be navigated to by the user.

**Comment by saziosu** [comment]
Added [django-phonenumbers](https://pypi.org/project/django-phonenumbers/) and [django-phonenumber-fields](https://django-phonenumber-field.readthedocs.io/en/latest/) to improve the user input form

**Comment by saziosu** [comment]
Added the link to `add-book` on the front end in index.html for logged in users.
If the user is not logged in they are encouraged to signup and login.

**Comment by saziosu** [comment]
Added LoginRequiredMixin and updated the index.html template to redirect logged out users to the login page.
