### ISSUE TITLE
USER STORY: Edit Book Posts

### ISSUE THREAD

**Issue by saziosu** [saziosu/book-swap#8]
**Epic:** #5 

As a **User**, I can **edit my book post** so that I can **update my information**

**Acceptance Criteria:**

- Users must be able to edit the book information
- Users should be able to mark the book as unavailable, to confirm the book is reserved
- Only the user that created the book post can edit it

**Tasks:**

- [x] Create the UpdateView for updating the post
    - [x] Within this view, only allow the user that made the post to update
- [ ] Set up the book_detail.html template to only allow the user that owns the book to view the edit button
- [x] Wire up the url

**Comment by saziosu** [comment]
Updated this ticket to its own User Story, I will be adding a new User Story for deleting posts.

**Comment by saziosu** [comment]
Added the BookUpdateView and set up the UserPassesTestMixin and the LoginRequiredMixin to only allow the user that owns the post to edit it.
The url is wired up and running.
Tested this out and I was able to successfully edit the post.

**Comment by saziosu** [comment]
Added the edit button to both index.html and post_detail.html
This is only visible to the user that created the post.
