### ISSUE TITLE
USER STORY: View Books

### ISSUE THREAD

**Issue by saziosu** [saziosu/book-swap#9]
**Epic:** #5 

As a **User**, I can **view other book posts** so that I can **decide which book I would like to swap with**

**Acceptance Criteria:**

- The user must be able to view other book posts
- The user must be authenticated to view other user's contact details

**Tasks:**

- [x] Create the template for post views
    - [x] Set up the template to only show contact details to authenticated users
- [x] Create the models and views for viewing posts
- [x] Wire up the url

**Comment by saziosu** [comment]
Added the model for getting the information from the user on the book.
Had some trouble with the phone number so I plan to come back to this later

**Comment by saziosu** [comment]
Added a test post and added the views and urls to view it on the front end.
I have used some of the templates from the previous django project to allow it to be viewed.
The style and content of the templates will be updated at a later date.

**Comment by saziosu** [comment]
Updated index.html to show the date the book was posted on the front end.
I also added an a tag so that when the card is clicked it will move to the page with more details from that post.
I plan to also show if the book is reserved on index.html so that the user can see if its already taken

**Comment by saziosu** [comment]
Added the BookView to views.py, added the urls for this also to urls.py and set up the book-detail.html to view the content of the book post.

**Comment by saziosu** [comment]
After working on account creation, I set up book-detail.html so that only authenticated users can view the contact details of the post owner

**Comment by saziosu** [comment]
Realised there is a small bit more to do on this, so I have re-opened it.
I have changed models.py to select the condition from a list of options for consistency.
I have also updated index.html and book_detail.html to clearly mark if the book has already been reserved

**Comment by saziosu** [comment]
Updated book_detail.html  to show the condition of the book
